# site title
title: JQ

# user name or organization name
user: kkxujq

# issue repository
repository: kkxujq.github.io

# multi-author
authors: 

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 9#42a9490815be148747715b30b3f7560e3965969

# posts per page
perpage: 20


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
